version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Install node modules'
          command: 'yarn'
      - persist_to_workspace:
          root: ~/repo
          paths: .
  commit-lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Lint commit messages'
          command: 'yarn commit:ci'
  format-lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Prettier lint'
          command: 'yarn format:ci'
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Build service'
          command: 'yarn build'
      - persist_to_workspace:
          root: ~/repo
          paths: ./dist
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - deploy:
          name: Deploy to S3
          command:
            aws s3 sync ./dist s3://baguette-app.request.network --acl public-read --delete
workflows:
  version: 2
  build:
    jobs:
      - install
      - commit-lint:
          requires:
            - install
      - format-lint:
          requires:
            - install
      - build:
          requires:
            - install
            - commit-lint
            - format-lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master