version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Install node modules'
          command: 'yarn'
      - persist_to_workspace:
          root: ~/repo
          paths: .
  commit-lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Lint commit messages'
          command: 'yarn commit:ci'
  format-lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Prettier lint' 
          command: 'yarn format:ci'
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
           at: ~/repo
      - run:
          name: 'Build service' 
          command: 'yarn build'


workflows:
  version: 2
  build:
    jobs:
      - install
      - commit-lint:
          requires:
            - install
      - format-lint:
          requires:
            - install
      - build:
          requires:
            - install
            - commit-lint
            - format-lint